// Mocks generated by Mockito 5.4.5 from annotations
// in ecommerce_flower_app/test/features/auth/domain/usecase/verify_reset_code_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ecommerce_flower_app/core/utils/datasource_excution/api_result.dart'
    as _i4;
import 'package:ecommerce_flower_app/features/auth/data/model/forget_password/forget_password_request_dto.dart'
    as _i5;
import 'package:ecommerce_flower_app/features/auth/data/model/reset_password/reset_password_request_dto.dart'
    as _i8;
import 'package:ecommerce_flower_app/features/auth/data/model/verify_reset_code/verify_reset_code_request_dto.dart'
    as _i7;
import 'package:ecommerce_flower_app/features/auth/domain/repo/auth_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> forgetPassword(
    _i5.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequestDto]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#forgetPassword, [forgetPasswordRequestDto]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> verifyResetCode(
    _i7.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequestDto]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#verifyResetCode, [
                  verifyResetCodeRequestDto,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> resetPassword(
    _i8.ResetPasswordRequestDto? resetPasswordRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequestDto]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequestDto]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
