// Mocks generated by Mockito 5.4.5 from annotations
// in ecommerce_flower_app/test/features/auth/data/data_source/remote/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:ecommerce_flower_app/features/auth/data/api/auth_retrofit_client.dart'
    as _i7;
import 'package:ecommerce_flower_app/features/auth/data/model/forget_password/forget_password_request_dto.dart'
    as _i11;
import 'package:ecommerce_flower_app/features/auth/data/model/forget_password/forget_password_response_dto.dart'
    as _i4;
import 'package:ecommerce_flower_app/features/auth/data/model/login/request/login_request_dto.dart'
    as _i9;
import 'package:ecommerce_flower_app/features/auth/data/model/login/response/login_response_dto.dart'
    as _i2;
import 'package:ecommerce_flower_app/features/auth/data/model/register/register_request_dto/register_request_dto.dart'
    as _i10;
import 'package:ecommerce_flower_app/features/auth/data/model/register/register_response_dto/register_response_dto.dart'
    as _i3;
import 'package:ecommerce_flower_app/features/auth/data/model/reset_password/reset_password_request_dto.dart'
    as _i13;
import 'package:ecommerce_flower_app/features/auth/data/model/reset_password/reset_password_response_dto.dart'
    as _i6;
import 'package:ecommerce_flower_app/features/auth/data/model/verify_reset_code/verify_reset_code_request_dto.dart'
    as _i12;
import 'package:ecommerce_flower_app/features/auth/data/model/verify_reset_code/verify_reset_code_response_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterResponseDto_1 extends _i1.SmartFake
    implements _i3.RegisterResponseDto {
  _FakeRegisterResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResetCodeResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDto_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRetrofitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRetrofitClient extends _i1.Mock
    implements _i7.AuthRetrofitClient {
  MockAuthRetrofitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.LoginResponseDto> login(_i9.LoginRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue:
            _i8.Future<_i2.LoginResponseDto>.value(_FakeLoginResponseDto_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i8.Future<_i2.LoginResponseDto>);

  @override
  _i8.Future<_i3.RegisterResponseDto> signUp(
          _i10.RegisterRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [request],
        ),
        returnValue: _i8.Future<_i3.RegisterResponseDto>.value(
            _FakeRegisterResponseDto_1(
          this,
          Invocation.method(
            #signUp,
            [request],
          ),
        )),
      ) as _i8.Future<_i3.RegisterResponseDto>);

  @override
  _i8.Future<_i4.ForgetPasswordResponseDto> forgetPassword(
          _i11.ForgetPasswordRequestDto? forgetPasswordRequestDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [forgetPasswordRequestDto],
        ),
        returnValue: _i8.Future<_i4.ForgetPasswordResponseDto>.value(
            _FakeForgetPasswordResponseDto_2(
          this,
          Invocation.method(
            #forgetPassword,
            [forgetPasswordRequestDto],
          ),
        )),
      ) as _i8.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i8.Future<_i5.VerifyResetCodeResponseDto> verifyResetCode(
          _i12.VerifyResetCodeRequestDto? verifyResetCodeRequestDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [verifyResetCodeRequestDto],
        ),
        returnValue: _i8.Future<_i5.VerifyResetCodeResponseDto>.value(
            _FakeVerifyResetCodeResponseDto_3(
          this,
          Invocation.method(
            #verifyResetCode,
            [verifyResetCodeRequestDto],
          ),
        )),
      ) as _i8.Future<_i5.VerifyResetCodeResponseDto>);

  @override
  _i8.Future<_i6.ResetPasswordResponseDto> resetPassword(
          _i13.ResetPasswordRequestDto? resetPasswordRequestDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequestDto],
        ),
        returnValue: _i8.Future<_i6.ResetPasswordResponseDto>.value(
            _FakeResetPasswordResponseDto_4(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequestDto],
          ),
        )),
      ) as _i8.Future<_i6.ResetPasswordResponseDto>);
}
